name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
          echo "$HOME/.local/bin" >> $GITHUB_PATH 
      - run: poetry install --no-interaction
      - run: |
          find ./docs -name '*.md' | while read file
          do
            # 見出しレベルを一段階下げる（ページタイトルのみをh1にするため）
            sed -ie "s|# |## |g" "${file}"

            # ページタイトルの設定
            name=`basename "${file}" .md`
            sed -ie "1s|^|#\ ${name}\n|" "${file}"

            # タグのエスケープ（見出しと認識されてしまうため）
            sed -ie "s|\([ \n\r\f\t]\+\)\(#[^ \n\r\f\t]\+\)|\1\`\2\`|g" "${file}"
          done
      - run: poetry run mkdocs gh-deploy --force
